### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by stellary123** [WinDanesz/LostBooks-II#3]
I cant seem to open any books and when I open a book and quill, the game crashes. This might be because my PC is bad, but do you have any fixes?

**Comment by WinDanesz** [comment]
Hey. Could you post a crash log? Thanks!

**Comment by stellary123** [comment]
Time: 8/24/20 11:33 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at toast.lostBooks.gui.GuiScreenBookUtil.<init>(GuiScreenBookUtil.java:80)
	at toast.lostBooks.client.ClientEventHandler.onGuiOpened(ClientEventHandler.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_111_ClientEventHandler_onGuiOpened_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:983)
	at net.minecraft.client.entity.EntityPlayerSP.func_184814_a(EntityPlayerSP.java:685)
	at net.minecraft.item.ItemWritableBook.func_77659_a(SourceFile:21)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1596)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by WinDanesz** [comment]
lostbooks version?

**Comment by stellary123** [comment]
The newest one, LostBooks-II-1.12.2-2.0.3.jar

**Comment by WinDanesz** [comment]
Thanks, is this on a dedicated server, or a singleplayer game?

**Comment by stellary123** [comment]
Singleplayer
